Temporarily fix "wrong Continuation" test failures
Related commit in compiler: https://github.com/JetBrains/kotlin/commit/486c6b3c15dfa245693c3df2c58c8353d75deddb

The fix is temporary because later we should use constants from compiler jars.
We will be able to use constants once 486c6b3c15dfa245693c3df2c58c8353d75deddb is reverted in the compiler

This commit fixes:
```
java.lang.AssertionError: Last parameter type of suspend function must be Continuation, but it is kotlin.coroutines.experimental.Continuation
at org.jetbrains.kotlin.idea.decompiler.stubBuilder.TypeClsStubBuilder.createFunctionTypeStub(TypeClsStubBuilder.kt:204)
at org.jetbrains.kotlin.idea.decompiler.stubBuilder.TypeClsStubBuilder.createClassReferenceTypeStub(TypeClsStubBuilder.kt:117)
at org.jetbrains.kotlin.idea.decompiler.stubBuilder.TypeClsStubBuilder.createTypeReferenceStub(TypeClsStubBuilder.kt:56)
```

Test example: org.jetbrains.kotlin.idea.caches.resolve.MultiPlatformHighlightingTestGenerated.testHeaderFunUsesStdlibInSignature

(Cherry-pick from IDEA-monorepo/1600f484)

GitOrigin-RevId: 8462134af0dc07d1de6cebb3c276cba783ba3683