Fix broken JPS
Stacktrace:
```
java.lang.IllegalStateException: We are in unit test mode! TestKotlinArtifacts must be available in such mode. Probably class was renamed or broken classpath
	at org.jetbrains.kotlin.idea.artifacts.KotlinArtifacts$Companion$instance$2.invoke(KotlinArtifacts.kt:16)
	at org.jetbrains.kotlin.idea.artifacts.KotlinArtifacts$Companion$instance$2.invoke(KotlinArtifacts.kt:9)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.idea.artifacts.KotlinArtifacts$Companion.getInstance(KotlinArtifacts.kt)
	at org.jetbrains.kotlin.idea.script.MainKtsScriptDefinitionSource.getDefinitionsClassPath(MainKtsScriptDefinitionSource.kt:18)
	at org.jetbrains.kotlin.idea.script.BridgeScriptDefinitionsContributor$definitions$1.invoke(BridgeDefinitionsContributor.kt:28)
...
```

GitOrigin-RevId: 60f6a0f3099ed22c3c6c87470e02a340c9c40864